# Generated by Django 3.2 on 2024-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
